### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by TPS** [kalaspuffar/secure-quick-reliable-login#103]
RFP @ https://gitlab.com/fdroid/rfp/issues/595, so this issue will track its inclusion.

_N.B.: @kalaspuffar This RFP seems pretty self-explanatory to me, but please ask if you need more info/detail/anything._

**Comment by kalaspuffar** [comment]
Hi @TPS 

Sound like a great idea. This repo is totally open source so if you want to download this and set up a build to F-Droid that is fine by me. A recommendation would be to use a commit called bumped version. Because of these signals a release to Google Play.

As this is an Alpha project with a focus on getting the functions in place it is still in heavy development so another commit could even not compile.

best regards
Daniel

**Comment by Poussinou** [comment]
F-Droid could build automatically your new versions (when you create one), so could you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)) in the future and when you're ready to release, it would be very helpful for us. You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).

**Comment by kalaspuffar** [comment]
Hi @Poussinou 

I've now tagged all builds and added Release information for multiple releases. Please advice if I missed anything in the flow.

Best regards
Daniel

**Comment by Poussinou** [comment]
It's ok

**Comment by TPS** [comment]
Just committed 4 hours ago to F-Droid Data, so should show up (relatively soonish) in main repo: https://gitlab.com/fdroid/fdroiddata/commit/811ae8022797ceed695515c412e9fdeaf89d024d

**Comment by TPS** [comment]
& [SQRL - Main (An implementation for SQRL (Secure Quick Reliable Login)](https://f-droid.org/app/org.ea.sqrl) is live! 🕺

**Comment by licaon-kter** [comment]
@kalaspuffar Any thoughts? https://f-droid.org/wiki/page/org.ea.sqrl/lastbuild_50
