### ISSUE TITLE
bug: button "Save identity" gives warning "Unable to create temporary"

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#209]
### Issue or error solving.

Saving identity fails, and it even didn't ask for permission to save to disk (*hint, hint*)

*Expected behavior*
Save to disk should work (preferably asking into which folder)

*Actual behavior*
"An error has occured" [sic]

*Steps to reproduce*
1. reinstall app
2. create identity
3. click Save identity

**Comment by kalaspuffar** [comment]
Strange you should be able to store database entries.

And the cache / temp area should not be restricted.

More investigation needed :)

**Comment by kalaspuffar** [comment]
Hi again @sesam 

This is a very strange occurrence. I've tried it multiple times and also read up on documentation and looked for other people that had a problem saving data to an SQLite database on a device without file permissions.

No one has reported this issue and Google doesn't document any requirements of any sort. Each App gets a database area that they may use without asking for storage permissions. And when exporting an identity I use the temporary caching area to create files. So I should not and don't want to add file permissions to the application if I don't have to.

So what make and model of phone are you using in order to get this error?

Best regards
Daniel

**Comment by IvarSnaaijer** [comment]
Might this be related to the issue I have ? 
When exporting the file I get 'it is not possible to create a temporary folder' 
Could you 'share' the item ?

**Comment by sengsational** [comment]
I got the "An error has occurred - Unable to create temporary directory for file to send, do you have too much data on the disk?"

On a fresh install, I created an identity, then used the print identity function and fiddled around with that a while, finally giving up on printing and saving it to a PDF.  I went to an email client and attached the PDF and sent it to myself.  Anyway...  Then I clicked "SHOW IDENTITY".  Nothing out of the ordinary there.  Then I clicked "SAVE IDENTITY" the first time, and I got a list of apps on my phone, then hit the back to see why I didn't choose this the first time.  So a side "problem" is that it isn't named "SHARE IDENTITY" and why it didn't have the typical android share icon.

The error message came up the 2nd time I clicked "SAVE IDENTITY", and `I/System.out: /data/user/0/org.ea.sqrl/cache/sqrltmp` popped up in the Logcat.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

Awesome feedback. Your deduction seems reasonable. I'll look into this issue as soon as possible. And you are right, share identity might be better. 

Adding icons could also be a good addition. Just wondering what icon to use for showing? An QR code ? :/

**Comment by sengsational** [comment]
When you press the save button, it shows the apps that I usually get when I press the share icon: 
[https://images.freecreatives.com/wp-content/uploads/2017/01/Android-Share-Icon.jpg](url)

**Comment by sesam** [comment]
for the icon, maybe the ["reveal password" icon from FontAwesome](https://fontawesome.com/icons/eye) is a good starting point.

**Comment by sengsational** [comment]
Although I've used various source control applications over the years, this would be the first open source project I've participated in.  I made a change to the code on my machine, then did a commit and push.  If this isn't the right set of actions, please advise.  In the various corporations I worked, there were lots of rules surrounding the process of testing, committing changes, etc, so I'm ready to do a bit of reading on the process, once I know where to look.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

Thank you for your contribution. Well, I think you've done mostly right. The thing you do in git is that you create a separate branch, commit your changes to that branch, push that branch to Github. And then you can create a pull request on those changes that I can review and test.

There will be some automated tests run on your commit as well but I've not written that many tests for the application so far because the code has not been stable until now.

I've done some videos on how to work with git if you want to learn more.

https://youtu.be/_hf_Al8ykq8
https://youtu.be/OQjlKVmkjtI
https://youtu.be/pAlO5F-ML7E

Thank you for your time.

Best regards
Daniel

**Comment by sengsational** [comment]
Thanks for the hand-holding.  I'll try and get up to speed on the process soon.

**Comment by IvarSnaaijer** [comment]
Just tested in 0.13.3  works for me now. Thanx

**Comment by sesam** [comment]
yay!
