### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#247]
Great app! Could you enlarge it's icon? On the Nexus 7 it's 1/4 size of other apps' icons.

**Comment by sengsational** [comment]
In Android Studio using image asset studio (https://developer.android.com/studio/write/image-asset-studio) , I clicked on the `res` folder, selected 'New > Image Asset`, and using the sqrl_print_logo.png, the tool generated ic_launcher, ic_launcher_foreground, and ic_launcher_round for various resolutions.  This might not be the direction to go, since vector XML is so much more efficient, but I saved it to my fork.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

First of I don't use the sqrl_print_logo more than for the printing process.

The icon used for the app is ic_sqrl_icon_vector_outline.xml

An SVG file should be displayed sharp on all devices. So we need to figure out why it's showing badly on Nexus 7 and perhaps it's some DPI or another aspect that we need to create a new icon for.

Good first step through to create icons for different platforms. But I want to keep the app small and lean so extra image files are not the solution except when it's required.

Best regards
Daniel

**Comment by sengsational** [comment]
I like the vector idea too rather than a raft of png files of different sizes, that's why I abandoned the changes generated by asset studio.

I did confirm on a simulator that the icon is smaller then normal on a Nexus 7 (not 1/4, but maybe 25% smaller than on my physical Moto G).  

I'll look into the Android controlled sizing of vector graphics in icons.

**Comment by kalaspuffar** [comment]
The new circular icon will not display at all on my old Android 18 (Samsung S5)

**Comment by sengsational** [comment]
This is not a problem with `android:roundIcon`, but instead a problem with using **vector graphics for a launch icon**.  Different problem.  I'll open a new issue.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

Are you sure? I'm pretty sure that the icon was present before the merge. Might have been just me. But if that is the case then I think we will keep it. Vector graphics are such a benefit for users and a little downside for the 1% users that have really old phones not supporting vector drawables.

Then again VectorDrawableCompat should have support back to API 14 :/

Best regards
Daniel

**Comment by sengsational** [comment]
We can close this issue and continue the discussion in #283, where I can continue to explore how the vector graphic launch icons work (or don't) on old API's.
