### ISSUE TITLE
SQRL forum requires 2 scans to login

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#250]
Reported by kylok

Hello, I've been trying out the forum login with the Android app and run into a consistent problem.

1. Completely logout of the sqrl.grc.com website.
2. Remove Quickpass from the SQRL andorid app.
3. Scan the SQRL Qr code on the website.
4. Input my password.
Result: success on the android app, but login doesn't occur.

1. Rescan the QR code.
2. use the fingerprint sensor for Quickpass.
Result: Website finally loads up.

So there seems to be no message sent to the website after step 4.
Runing on Android Sony Xperia phone with Android Pie (9)

**Comment by IvarSnaaijer** [comment]
I was not able to reproduce this problem with 0.13.4 (Samsung S7, Android 8, Firefox 65.0 64bit, Ubuntu 18.04)

**Comment by sengsational** [comment]
I experienced something like this (greater than one attempt required to login on the forum site), but I was watching the Logcat at the time and it didn't look as if the problem was on the Android side.  In other words, I presumed that the problem was on the forum software login side.

[https://sqrl.grc.com/threads/just-a-ramble-on-my-first-day-with-sqrl.336/post-1851](https://sqrl.grc.com/threads/just-a-ramble-on-my-first-day-with-sqrl.336/post-1851)

**Comment by kalaspuffar** [comment]
I think this was due to a server issue and should now be solved.
