### ISSUE TITLE
Handle .sqrl file intent

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#260]
Using file intent and the import activity to import identity files into application.

**Comment by alexhauser** [comment]
Hi @kalaspuffar , 

is this something you're actively working on? Otherwise I could offer some help here as well.

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Nope, I tried but have not had time to look into this yet. Tried a few different mime-types but never got it to trigger. If I find how to trigger the share function it should be trivial to enable import.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I tried to get it to trigger for the .sqrl file extension only, and indeed this seems to be impossible to do, at least on anything >= Nougat:

In the SO question https://stackoverflow.com/questions/3760276/android-intent-filter-associate-app-with-file-extension/12915288 someone posts:

> So from what I've seen, tried and read, Android simply cannot distinguish between file-extensions and the pathPattern tag is basicly a gigantic waste of time and energy. If you are fortunate enough to only need files of a certain mime-type (say text, video or audio), you can use an intent-filter with a mime-type. If you need a specific file-extension or a mime-type not known by Android however then you're out of luck.

And another one:

> Android 7.0 Nougat no longer permits file sharing between apps using a file URI. A content URI must be used. However, a content URI does not allow a file path to be shared, only a mime type. So you cannot use a content URI to associate your app with your own file extension.

Which leaves us with mime types only I guess. And since the mime type for our .sqrl files is probably undefined or not known to Android, it looks like it's "all or nothing" here. The intent-filter does trigger if we don't specify any special mime type, but this means SQRL will be offered for *any* file type that is being shared. Yuck!

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Yes, that is not a good solution or a nice solution but if we only have one we might need to support it for now. But we need to check the file if it has a header or else show a nice error message so users aren't confused by this feature.

Best regards
Daniel
