### ISSUE TITLE
strength indicator

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#278]
Add password strength indicator to show password strength. Don't add any requirement for password length just recommendation.

**Comment by silversword411** [comment]
Not sure how to implement, but these look like 3 different possibilities:
https://github.com/yesterselga/password-strength-checker-android
https://blog.davidmedenjak.com/android/2017/01/14/password-strength.html
http://crazygeeksblog.com/2017/10/password-strength-validation-checker-in-android-with-example/

**Comment by kalaspuffar** [comment]
Hi @silversword411 

Great input. Seems like the last link is pretty much what I was thinking of. Having a progress bar showing some strength indication maybe with some colors and perhaps some descriptive text.

And then make some quantitive calculation on the strength. Not keen on adding a library to solve this "trivial" problem. Maybe we can take inspiration from GRC password strength check.

https://www.grc.com/haystack.htm

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi,

I am working on this and a PR should come in shortly.

However, this is not as "trivial" as it looks at first sight. Measuring password strength only by password length and use of character types (upper/lower/digit/symbol) like Steve's password haystack would fail to detect a whole class of really bad passwords, like commonly used passwords, common keyboard patterns, guessable passwords etc. Steve even notes in big letters that password haystack is NOT a password strength meter.

Now, the most robust thing would probably be to include a library like https://github.com/nulab/zxcvbn4j, but it is large and supposedly also slow, so I guess it would probably be overkill.

That's why I am working on a hybrid solution, using a simple algorithm based on password length and character classes, but additionally checking against a list of the 10.000 most common passwords from https://github.com/danielmiessler/SecLists.

What do you guys think?

Here are some preliminary screenshots:
![01](https://user-images.githubusercontent.com/4005543/55961901-23e7d800-5c70-11e9-8b88-f00b9de78058.JPG)
![02](https://user-images.githubusercontent.com/4005543/55961902-24806e80-5c70-11e9-9252-0091e30d0519.JPG)
![03](https://user-images.githubusercontent.com/4005543/55961903-24806e80-5c70-11e9-8ec4-19c8aced3178.JPG)
![04](https://user-images.githubusercontent.com/4005543/55961904-24806e80-5c70-11e9-925f-60b356d4d37f.JPG)

**Comment by jroedel** [comment]
Sounds like a great idea to me!

Just a note on English sensitivities, "bad strength" sounds weird to me. If the noun is "strength" I would go with Low, Medium, High. I checked in Keepass and they use "Quality". They don't use adjectives but you could do Poor, Medium, Good, Great, Excellent (how ever many you want).

**Comment by alexhauser** [comment]
Thanks for the input @jroedel, since English is not my first language, I'm grateful for any help in that regard!

**Comment by alexhauser** [comment]
PR merged, issue can be closed.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Well, I think it's almost done :)

We need to add it to reset password and change password dialogs and perhaps more that I can't remember off the top of my head.

Best regards
Daniel

**Comment by alexhauser** [comment]
Right, @kalaspuffar , I'll check and open a new PR.
