### ISSUE TITLE
Remove quickpass notification

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#302]
### Feature request.

Quickpass notification is shown in the notification bar and enables the removal of quickpass from the phone to increase security.

This feature should be removed because it's confusing to users.

**Comment by alexhauser** [comment]
Hi @kalaspuffar , just quickly checking back if I understand the corresponding code right: 

It looks to me as if all the logic for building the notification as well as for calling the JobScheduler/AlarmManager to clear the QuickPass after the specified delay are located in `showClearNotification()` within the `LoginBaseActivity`. Is that correct or did I miss an important part somewhere else?

If yes, would it be a good strategy to separate out the JobScheduler/AlarmManager code into its own method and then replace all the calls to `showClearNotification()` to this new method. This way, clearing the QuickPass after the delay would still be triggered without the notification being built and displayed.

We could then leave the `showClearNotification()` method there but unused, because you never know. :)

Thanks in advance for your input and best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Sounds like a reasonable approach. And your assumptions are correct. 

Keep in mind that the quickpass has both a visual component showing the number of chars that should be entered as well as a string in preferences that needs clearing if the end up in a case where the old key has become invalid. So this needs testing to validate that the key actually is cleared after refactoring.

Best regards
Daniel

**Comment by alexhauser** [comment]
Thanks for the additional info, @kalaspuffar !
I'll look into this as soon as I have time.
