### ISSUE TITLE
QuickPass state is lost

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#340]
### Issue or error solving.

@sengsational reports:

> By the way, the app I have (a week or so old maybe) consistently loses it's QuickPass state, even though I have idle timeout set to 26 days. I think it's those instance variables in the SQRL object. I've learned (the hard way), that zero is the right number of instance variables in Android :)

**Comment by sengsational** [comment]
This may have been due to my setting the idle timeout "too high" (#330).  I've set it to a value that's lower now, and have had no obvious issues (but I haven't purposefully tested this and I've had a wild ride with all of the branches/versions I've been testing). 

I'll start working on a fix for #330

**Comment by alexhauser** [comment]
Thanks for the info, Dale. Good to hear that this is a non-issue. 
I'll close this for now.

**Comment by sengsational** [comment]
Today I was prompted for the first 4 characters, and it gave me an error.  The first four of my password are pretty easy, so I don't think I typed it wrong, but I'll keep an eye on it.  

We can keep this closed unless I get some more substance to it.
