### ISSUE TITLE
Button colors

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#360]
Coloring bug.

Repro:
1. open the app - the center button is dark purple.
2. open help
3. close help - the main page center button is a lighter purple color

Expected:
the button primary color to stay the same on all primary/important parts of the app.

It seems all buttons change to the lighter purple color, and only the identity name (underlined, looks like a link) stays the same.

**Comment by alexhauser** [comment]
Hi @sesam,

I can't reproduce this. Which repo/branch/version have you checked out? Or does it happen on the release version? Also, can you please post pre-post screenshots so that we can determine what exact colors are involved?

Fyi, I am working on a better dark theme version of the main screen (SimplifiedActivity) at the moment where I will address some issues I have noticed on the main scan button. It would be good if we could catch this so I could integrate a fix there.

**Comment by sesam** [comment]
Hi, yesterday night I got the buttons all pink. Today it doesn't happen. Maybe a screen brightness/adaptation bug and not something the app can influence.
I filed this issue in case anyone knew of code that changes theme colors. Since you're working on a new theme any related code will anyway be revisited, and no need to track this separately. Closing for now :)
