### ISSUE TITLE
Rescue code show contrast issue

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#364]
### Issue or error solving.

*Short description of the issue*

The contrast is not good on most devices but really bad on an old Samsung Galaxy 5
![Screenshot_2019-06-26-21-29-45](https://user-images.githubusercontent.com/1424084/60209291-9bcea300-985a-11e9-88f1-0ec296db6a02.png)

*Expected behavior*

Rescue code should be visible

*Actual behavior*

Rescue code is not visible

*Steps to reproduce*

Create a new identity.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Can you look at this? Should not be too hard I guess.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar , I'm on it.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I have a fix ready for this but don't know how to test it on a Galaxy S5 as I don't own one. Is there a way of testing this in the emulator or have you tested this on real hardware yourself? In case of the the latter, shall I just post a PR so that you can test it on the Galaxy S5?

Best regards, 
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I've tested it on a real device, so prepare a PR and I'll test it.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar, did the fix work on the Galaxy S5 as well?

**Comment by kalaspuffar** [comment]
Worked like a charm.
