### ISSUE TITLE
Some activities don't honor night mode

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#367]
### Issue or error solving.

While fixing the rescue code contrast issue and testing the fix in night mode, I noticed that some of our activities will not automatically switch to dark mode while others do.

*Expected behavior*
All activities switch to dark mode if enabled in the Android display settings in Android Q

*Actual behavior*
Only some of the activities switch to dark mode. For example, `StartActivity`, `RescueCodeShowActivity` as well as others in the `create` folder will not switch to dark mode unless manually set with `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);`.

*Steps to reproduce*
- Spin up a virtual device running Android Q 
- Enable dark mode in the Android display settings
- Open the app, and create a new identity.
You will notice that some of the activities have switched to dark mode while others have not

I thought extending `AppCompatActivity` (which all of our apps do by directly or indirecltly extending `CommonBaseActivity`) would be enough for all our activities to support this out of the box. 

What's going on here?

**Comment by sengsational** [comment]
On my physical phone (8.1.0), I never had any night mode things showing up, no matter what time of day it was.  I saw that my phone was returning -1 when I asked for the default night mode.  So I added some code (in https://github.com/sengsational/secure-quick-reliable-login/tree/dark_mode_scanning) that runs this on startup:

            uiModeManager.enableCarMode(0);
            uiModeManager.setNightMode(UiModeManager.MODE_NIGHT_AUTO);
            if (carModeWasOff) uiModeManager.disableCarMode(0);

It was strange, but without enabling car mode, the set night mode didn't have an effect.  I'm not going to have time now to try this on a virtual device.  You could try it and let me know.  Also, you might notice that in the version in that branch, you can now tap repeatedly and quickly on the home screen to change night modes.  This is required for me in 8.1.0 because there is nowhere in the UI to set night mode 'on'.

**Comment by alexhauser** [comment]
Hi @sengsational,

wow, I must have missed your post on this one, so sorry for the late reply and thanks for your input!

I'm going to look at what you've suggested asap and report back. 

Cheers, Alex
