### ISSUE TITLE
Scanning identity from a darkmode device

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#380]
### Issue or error solving.

*Short description of the issue*
When the phone is in darkmode the QR Code will show white on dark background which work less well with some devices.

*Expected behavior*
Scanning a QR code should work on an older device when presented with a QR Code from a new device in darkmode.

*Actual behavior*
Scanning fails.

*Steps to reproduce*
1. Set phone 1 in dark mode.
2. Try to scan QR code from another device.

**Comment by kalaspuffar** [comment]
A solution could be to set a thin border white around the QR code. That might work.

**Comment by sengsational** [comment]
How do you set the phone to dark mode?  My phone always seems have the same color scheme, no matter what time of day it is.  I suppose I could dig into the code, but in case it's something really easy that I'm overlooking, I thought I'd ask.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

Some phones can have dark mode during the evening.

With the new Q release you can turn dark mode on for all uses and apps. I don't know if all have this beta installed. If not then I can look into it :)

Best regards
Daniel

**Comment by sengsational** [comment]
I did a bit of work on this.  The basic problem was just a couple of lines in the `activity_show_identity.xml`, but in order to test it on my phone, I had to figure out a way to get my phone running in night mode.  I added a method that runs on startup to put the phone into automatic mode (my phone isn't in that by default).  I won't know until sundown if that works :-)  But the way I was able to test was by adding a thing that toggles the night mode; by tapping repeatedly/quickly on the app, it will toggle night mode.  

There are hard-coded strings in the method, but I didn't know if it would be advisable to leave the app-tester-only code in the app, or remove it, so didn't want to bother with adding those to all of the language string files.

No PR at this time because there's more to be discussed, but I did push the code to my repo: 
https://github.com/sengsational/secure-quick-reliable-login/tree/dark_mode_scanning

**Comment by kalaspuffar** [comment]
Hi @sengsational 

```
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
```

Maybe forcing the mode during development could be a thing?

Best regards
Daniel

**Comment by sengsational** [comment]
I tried that one, but `UiModeManager` seemed to work better for me.

**Comment by alexhauser** [comment]
Hi @sengsational , 

may I ask what is keeping you from posting a PR at this point? I think it would make it easier for everyone to get an understanding of what you were referring to in your penultimate post.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @sengsational,

I can confirm that your fix of setting a padding of 20px around the qr code and setting the bgcolor to white solves the basic problem. I think you should post a PR for that fix. Please don't forget to apply the fix to the landscape version as well, it's currently only available in the portrait version in your repo.

As for the night mode toggling code you've added, this doesn't work for me. It always only shows `Setting night mode 'auto'`. Only when I enable night mode in Android Q display settings, it toggles to `no`, but doesn't seem to do anything. I also wouldn't want to add such code to anything that is going to be deployed to end users. I would suggest you just download an Android Q image and test on the emulator, where one can toggle night mode natively and more reliably in the settings. Also, the code that @kalaspuffar posted to manually enable/disable night mode for a particular activity should work reliably even on older APIs.

So I would suggest to strip out all the debugging code and post a PR for only the qr code layout fix.

**Comment by sengsational** [comment]
Thanks for the suggestions Alex. I think our thinking is aligned. There was no PR because, like you, I didn't like the night mode switching code going to the code base. I can generate a small PR with the white border soon. I haven't been on vacation, but got a document feed photo scanner and have scanned over 5000 photos, so that other project, still ongoing, has garnered my attention.

**Comment by alexhauser** [comment]
Thanks for confirming, Dale! There's no need to rush anything, so happy scanning! 😄
