### ISSUE TITLE
Nightmode activated randomly.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#403]
### Issue or error solving.

*Short description of the issue*

Some devices use day and night mode but don't activate it per default for different activities. So implementers need to tell the system that this activity support day and night cycle.

Code to add
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_AUTO);

*Expected behavior*
When a device with this feature is used at night all activities should switch to night mode.

*Actual behavior*
The night mode is only activated when you visit an activity with this line added. Example Rekey identity.

*Steps to reproduce*
1. Start app on a phone with Android Oreo during the evening.
2. Start screen should be in light mode
3. Goto identity management
4. Still light mode
5. Goto Rekey in the menu
6. Nightmode is active and all Activities will now be shown in darkmode.

**Comment by kalaspuffar** [comment]
Possiable duplicate of #367

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

thanks for adding additional details to the night mode topic. I have planned to look into this anyway and have bookmarked a good link regarding this topic: 
https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94

What I would like to do is set `MODE_NIGHT_AUTO` as default as described in your posting, but additionally give the user a chance to choose their default mode manually. This would require a "general setting" for the first time, so I held back on that because I wanted to discuss it with you guys first. 

What do you think about a global Day/Night mode switch for the app?

Best regards,
Alex

P.S.: Please note that I will head out for a short 3-4 day vacation with my familiy today. I will take my dev laptop with me, but I guess time for development will be limited!

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Bon voyage :)

I'm not sure if we need a switch in the app, later versions will have the option to decide on dark mode anyway. As a compromise we could add the switch for older devices but I'm not sure if it's worth the code involved.

Thoughts?

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @ kalaspuffar,

I agree that it's probably not worth the code bloat, let's proceed as suggested by you earlier and just fix the night mode issues.

Best regards,
Alex

**Comment by sengsational** [comment]
If the default mode is set in  `SqrlApplication.onCreate()`, isn't that all we need?  I do recall that this feature is jinky with various Android versions, so maybe not that easy.
