### ISSUE TITLE
progressionUpdater.endTimer() seems to be in the wrong place

### ISSUE THREAD

**Issue by smw1218** [kalaspuffar/secure-quick-reliable-login#433]
Just browsing your code and noticed this EncryptionUtils.java: line 237.

You're calling progressionUpdater.endTimer() on this line, but this is before the scrypt iterations loop. I think it should be on about line ~246. Likely only comes into play if there's a big cross-platform performance skew when migrating accounts so probably not urgent.

**Comment by kalaspuffar** [comment]
Hi @smw1218 

Thank you for looking at the code and trying to identify problems that we might have overseen.

I looked into the code and I believe it's correct as is. We run one iteration to see how long the encryption will be in order to show the user how much time is left. 

So we time one and then multiply that with how many iterations we need to run.

Hope this explanation helps.

Best regards
Daniel

**Comment by smw1218** [comment]
Thanks for the clarification.
Sorry, I've been looking at other implementations and I mistook this for a feature mentioned in the crypto doc about timing the iterations to make sure they match user time preference (in the case an identity has been imported from some other platform).
